version: '3.9'

services:
  booster_sim:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: booster_sim
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - WEBOTS_HOME=/usr/local/webots
      - LD_LIBRARY_PATH=/usr/local/webots/lib/controller
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
    # command: /root/Workspace/booster_sim/docker/entrypoint.sh
    stdin_open: true
    tty: true
